[package]
name = "podcatch_rust"
version = "0.5.2"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[package.metadata.deb]
name = "podcatch-rust"
priority = "optional"
section = "rust"
provides = "podcatch-rust"
extended-description = """\
CLI Podcatcher written in Rust."""

[dependencies]
deadpool = "0.8"
deadpool-postgres = "0.9"
dotenv = "0.15"
tokio-postgres = "0.7"
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"]}
rand = "0.8"
roxmltree = "0.14"
checksums = "0.9"
structopt = "0.3"
walkdir = "2.3"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
log = "0.4"
env_logger = "0.8"
crossbeam-utils = "0.8"
bytes = "1.0"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0"
tokio = {version = "1.0", features=["full"]}
async-trait = "0.1"
futures = "0.3"
derive_more = "0.99"
smartstring = "0.2"
itertools = "0.10"
envy = "0.4"
deadqueue = "0.2"
smallvec = "1.6"
refinery = {version="0.5", features=["tokio-postgres"]}
stack-string = { version="0.2", features=["postgres_types"] }
postgres_query = {git = "https://github.com/ddboline/rust-postgres-query", tag = "0.3.3-2", features=["deadpool"]}

[[bin]]
name = "podcatch-rust"
path = "src/podcatch_rust.rs"
doc = false
