[package]
name = "podcatch_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
dotenv = "0.14"
postgres = "0.15"
reqwest = "0.9"
url = "1.7"
rand = "0.6"
roxmltree = "0.6"
