[package]
name = "podcatch_rust"
version = "0.3.7"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
deadpool = "0.5"
deadpool-postgres = "0.5"
dotenv = "0.15"
tokio-postgres = "0.5"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"]}
rand = "0.7"
roxmltree = "0.11"
checksums = "0.6"
rayon = "1.3"
structopt = "0.3"
subprocess = "0.2"
walkdir = "2.3"
id3 = "0.5"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
cpython = "0.5"
log = "0.4"
env_logger = "0.7"
retry = "1.0"
crossbeam-utils = "0.7"
postgres_query = "0.3"
bytes = "0.5"
anyhow = "1.0"
thiserror = "1.0"
dirs = "2.0"
tokio = {version = "0.2", features=["full"]}
async-trait = "0.1"
futures = "0.3"
derive_more = "0.99"
inlinable_string = "0.1"

[[bin]]
name = "podcatch-rust"
path = "src/podcatch_rust.rs"
doc = false
