[package]
name = "podcatch_rust"
version = "0.4.5"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
deadpool = "0.5"
deadpool-postgres = "0.5"
dotenv = "0.15"
tokio-postgres = "0.5"
reqwest = {version="0.10", features=["cookies", "json", "rustls-tls", "stream"]}
rand = "0.7"
roxmltree = "0.13"
checksums = "0.6"
structopt = "0.3"
walkdir = "2.3"
id3 = "0.5"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
cpython = "0.5"
log = "0.4"
env_logger = "0.7"
crossbeam-utils = "0.7"
postgres_query = "0.3"
bytes = "0.5"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0"
tokio = {version = "0.2", features=["full"]}
async-trait = "0.1"
futures = "0.3"
derive_more = "0.99"
smartstring = "0.2"
itertools = "0.9"
envy = "0.4"
deadqueue = "0.1"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.3", features=["postgres_types"] }

[[bin]]
name = "podcatch-rust"
path = "src/podcatch_rust.rs"
doc = false
