[package]
name = "podcatch_rust"
version = "0.2.6"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
r2d2 = "0.8"
r2d2_postgres = "0.16"
dotenv = "0.15"
postgres = "0.17"
reqwest = {version="0.10", features=["cookies", "blocking", "json"]}
rand = "0.7"
roxmltree = "0.9"
checksums = "0.6"
rayon = "1.3"
structopt = "0.3"
subprocess = "0.2"
walkdir = "2.3"
id3 = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
cpython = "0.4"
log = "0.4"
env_logger = "0.7"
retry = "1.0"
crossbeam-utils = "0.7"
postgres_query = "0.3"
bytes = "0.5"
anyhow = "1.0"
thiserror = "1.0"
dirs = "2.0"

[[bin]]
name = "podcatch-rust"
path = "src/podcatch_rust.rs"
doc = false
