[package]
name = "podcatch_rust"
version = "0.1.18"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
dotenv = "0.14"
postgres = "0.15"
reqwest = "0.9"
rand = "0.7"
roxmltree = "0.7"
checksums = "0.6"
rayon = "1.2"
structopt = "0.3"
subprocess = "0.1"
walkdir = "2.2"
id3 = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
cpython = "0.3"
log = "0.4"
env_logger = "0.6"
retry = "0.5"

[[bin]]
name = "podcatch-rust"
path = "src/podcatch_rust.rs"
doc = false
